server:
  port: 9002

spring:
  application:
    name: consumer-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者将去访问的微服务名称（注册成功进nacos的微服务提供者,对应提供者的spring.application.name）
remote-service-url:
  provider-service-url: http://provider-server

management:
  endpoints:
    web:
      exposure:
        include: '*'